In [3]:
import numpy as np
import math as ma
import random as rdm
import sympy as sp
import pygame as pg

pygame 2.5.2 (SDL 2.28.3, Python 3.11.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


## Exercice 6.1 

In [5]:
def Vecteur_colonne(A):
    array = []
    for ligne in range(len(A)):
        for colonne in range(len(A[ligne])):
            array.append(A[colonne][ligne])
            vecteur_colonne = np.array([array])
    return vecteur_colonne.T

In [6]:
v = Vecteur_colonne(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
print(v)

[[1]
 [4]
 [7]
 [2]
 [5]
 [8]
 [3]
 [6]
 [9]]


In [7]:
def Matrice(V):
    n = int(ma.sqrt(len(V)))
    mat = np.zeros((n, n))
    l = 0
    for ligne in range(n):
        for colonne in range(n):
            mat[colonne][ligne] = V[l]
            l = l + 1
    return mat

In [8]:
m = Matrice(v)
print(m)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


C:\Users\Ludivine\AppData\Local\Temp\ipykernel_1992\2061964481.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  mat[colonne][ligne] = V[l]


## Exercice 6.2

In [9]:
def Croix(ligne, colonne, n):
    mat = np.zeros((n, n))
    mat[ligne][colonne] = 1
    if n > ligne + 1:
        mat[ligne + 1][colonne] = 1
    if ligne - 1 >= 0:
        mat[ligne - 1][colonne] = 1
    if n > colonne + 1:
        mat[ligne][colonne + 1] = 1
    if colonne - 1 >= 0:
        mat[ligne][colonne - 1] = 1
    return mat

In [10]:
print(Croix(1, 2, 5))

[[0. 0. 1. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Exercice 6.3

In [11]:
def gagner(matrice):
    tailleMatrice = len(matrice)
    for i in range(tailleMatrice):
        for j in range(tailleMatrice):
            if matrice[i][j]:
                return False
    return True

def matriceBinaire(matrice):
    tailleMatrice = len(matrice)
    for i in range(tailleMatrice):
        for j in range(tailleMatrice):
            matrice[i][j] = matrice[i][j] % 2
    return matrice

def Light_Out():
    taille = 2
    mat = np.zeros((taille, taille))
    for i in range(taille):
        for j in range(taille):
            mat[i][j] = rdm.randint(0, 1)
    print(mat)
    
    while not gagner(mat):
        ligne = int(input("Quelle ligne joué ?"))
        colonne = int(input("Quelle colonne joué ?"))
        mat = mat + Croix(ligne, colonne, taille)
        mat = matriceBinaire(mat)
        print("\n------------------------------\n")
        print(mat)
    print("Félicitation, vous avez gagné !")

In [14]:
Light_Out()

[[0. 1.]
 [0. 0.]]

------------------------------

[[1. 0.]
 [0. 1.]]

------------------------------

[[1. 1.]
 [1. 0.]]

------------------------------

[[0. 0.]
 [0. 0.]]
Félicitation, vous avez gagné !


## Exercice 6.4

In [15]:
def Matrice_Passage(n):
    mat_passage = []
    for i in range(n):
        for j in range(n):
            mat = Croix(j,i,n)
            mat = Vecteur_colonne(mat)
            mat_passage.append(mat)
    return np.transpose(mat_passage)
    


In [16]:
print(Matrice_Passage(2))

[[[1. 1. 1. 0.]
  [1. 1. 0. 1.]
  [1. 0. 1. 1.]
  [0. 1. 1. 1.]]]


## Exercice 6.5

In [17]:
solution_unique_det = []
for i in range (2,12):
    det = round(np.linalg.det(Matrice_Passage(i)[0]))%2
    if(det!=0):
        solution_unique_det.append(i)
print(solution_unique_det)

[2, 3, 6, 7, 8, 10]


## Exercice 6.6

In [18]:
mat_pass_3 = Matrice_Passage(3)
inv_mat_pass_3 = np.linalg.inv(mat_pass_3)
for i in range(9):
    for j in range(9):
        inv_mat_pass_3[0][i][j] = round(inv_mat_pass_3[0][i][j],0)%2
print(inv_mat_pass_3)


[[[0. 1. 0. 1. 0. 0. 0. 0. 1.]
  [1. 0. 1. 0. 0. 0. 0. 1. 0.]
  [0. 1. 0. 0. 0. 1. 1. 0. 0.]
  [1. 0. 0. 0. 0. 1. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 1. 0. 0. 0. 0. 1.]
  [0. 0. 1. 1. 0. 0. 0. 1. 0.]
  [0. 1. 0. 0. 0. 0. 1. 0. 1.]
  [1. 0. 0. 0. 0. 1. 0. 1. 0.]]]


## Exercice 6.7

In [19]:
def Solution(A):
    vec_col = Vecteur_colonne(A)
    mat_pass = Matrice_Passage(len(A))
    
    inv_mat_pass = np.linalg.inv(mat_pass[0])
    vec_col = np.dot(inv_mat_pass, vec_col)
    vec_col = np.round(vec_col)

    for i in range(len(vec_col)):
        for j in range(len(vec_col[i])):
            vec_col[i][j] = vec_col[i][j]%2
        
    return Matrice(vec_col)


In [20]:
taille = 3
mat = np.zeros((taille, taille))

mat[1][0] = 1
mat[1][1] = 1
mat[2][1] = 1

print("Matrice initiale : ")
print(mat)
sol = Solution(mat)
print("Solution : ")
print(sol)

Matrice initiale : 
[[0. 0. 0.]
 [1. 1. 0.]
 [0. 1. 0.]]
Solution : 
[[0. 1. 1.]
 [0. 1. 1.]
 [1. 0. 0.]]


C:\Users\Ludivine\AppData\Local\Temp\ipykernel_1992\2061964481.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  mat[colonne][ligne] = V[l]
